# Generated by Django 5.1.4 on 2025-02-28 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageArtStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ImageArtStyleCategory', to='gallery.imagecategory')),
            ],
            options={
                'verbose_name': 'Estilo de Arte',
                'verbose_name_plural': 'Estilos de Arte',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='style',
            field=models.ManyToManyField(blank=True, to='gallery.imageartstyle'),
        ),
    ]
