# Generated by Django 5.1.4 on 2025-02-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_imageartstyle_image_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageartstyle',
            name='description',
            field=models.TextField(default='No description', verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
