# Generated by Django 5.1.4 on 2025-02-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_alter_image_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='style',
            field=models.ManyToManyField(blank=True, to='gallery.imageartstyle', verbose_name='Estilo(s)'),
        ),
    ]
