# Generated by Django 5.1.4 on 2025-01-16 00:18

import utils.validators.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesetup', '0006_alter_menulink_site_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='data/assets/favicon/%Y/%m/', validators=[utils.validators.model.validate_png]),
        ),
    ]
